//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTiming
    {
        public int EventTimingID { get; set; }
        public System.DateTime EventTiming1 { get; set; }
        public int Customer_ID { get; set; }
        public int ServicesPicture_ID { get; set; }
        public bool isActive { get; set; }
    }
}
