//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTiming
    {
        public int EventTimingID { get; set; }
        public System.DateTime EventDateTime { get; set; }
        public int Customer_ID { get; set; }
        public int ServicesPicture_ID { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal Advance { get; set; }
        public decimal Balance { get; set; }
        public bool isActive { get; set; }
        public int CreatedByUser_ID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public Nullable<int> ModifiedByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
    }
}
