//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membership_Webpageurls
    {
        public int WebPageUrlID { get; set; }
        public Nullable<int> WebPage_ID { get; set; }
        public string Url { get; set; }
    }
}
