//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServicesID { get; set; }
        public string ServicesTitle { get; set; }
        public string ServicesDescription { get; set; }
        public string ServicesMainImage { get; set; }
        public int CreatedByUser_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public bool isActive { get; set; }
    }
}
