//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesPicture
    {
        public int ServicesPictureID { get; set; }
        public string ServicesPictureTitle { get; set; }
        public string ServicesPictureDescription { get; set; }
        public string ServicesPicturePath { get; set; }
        public bool isActive { get; set; }
        public int SubServices_ID { get; set; }
    }
}
