//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubServices
    {
        public int SubServiceID { get; set; }
        public string SubServiceTitle { get; set; }
        public Nullable<bool> isActive { get; set; }
        public int Service_ID { get; set; }
        public Nullable<int> EventType_ID { get; set; }
    }
}
