//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventGallery
    {
        public int EventGalleryID { get; set; }
        public string EventGalleryTitle { get; set; }
        public string EventGalleryPicture { get; set; }
        public bool isActive { get; set; }
    }
}
