//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceMenu
    {
        public int PriceMenuID { get; set; }
        public string PriceMenuTitle { get; set; }
        public long Price { get; set; }
        public string PriceMenuPicture { get; set; }
        public bool isActive { get; set; }
        public string FoodName1 { get; set; }
        public string FoodName2 { get; set; }
        public string FoodName3 { get; set; }
        public string FoodName4 { get; set; }
        public string FoodName5 { get; set; }
        public string FoodName6 { get; set; }
        public string FoodName7 { get; set; }
        public string FoodName8 { get; set; }
        public string FoodName9 { get; set; }
        public string FoodName10 { get; set; }
        public string FoodName11 { get; set; }
        public string FoodName12 { get; set; }
        public string FoodName13 { get; set; }
        public string FoodName14 { get; set; }
        public string FoodName15 { get; set; }
        public string FoodName16 { get; set; }
        public string FoodName17 { get; set; }
        public string FoodName18 { get; set; }
        public string FoodName19 { get; set; }
        public string FoodName20 { get; set; }
        public int CreatedByUser_ID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
