//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplication
    {
        public int ApplicationID { get; set; }
        public int Job_ID { get; set; }
        public string ApplicantName { get; set; }
        public string FatherHusbandName { get; set; }
        public string CNIC { get; set; }
        public string MobileNo { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public Nullable<double> Experience { get; set; }
        public string MailAddress { get; set; }
        public int DomicileDistrict_ID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public Nullable<System.DateTime> CheckDateTime { get; set; }
        public string TotalExperience { get; set; }
        public string CVPath { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Gender { get; set; }
        public int EnterByUser_ID { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
    }
}
