//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public int BookID { get; set; }
        public string BookCode { get; set; }
        public string BookTitle { get; set; }
        public string Author { get; set; }
        public string BookISBN { get; set; }
        public string Barcode { get; set; }
        public string Edition { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string VehicleNo { get; set; }
        public int EnterByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public int Vendor_ID { get; set; }
        public bool IsActive { get; set; }
        public decimal Total { get; set; }
    }
}
