//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClient
    {
        public int ClientID { get; set; }
        public string ClientName { get; set; }
        public string ClientLogo { get; set; }
        public Nullable<int> ClientType { get; set; }
        public Nullable<bool> ShowOnHome { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> EnterByUser_ID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
