//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDownload
    {
        public int DownloadID { get; set; }
        public string DownloadTitle { get; set; }
        public string DownloadPath { get; set; }
        public int EnterByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public bool IsActive { get; set; }
        public string Details { get; set; }
    }
}
