//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEvent()
        {
            this.tblImages = new HashSet<tblImage>();
        }
    
        public int EventID { get; set; }
        public string EventTitle { get; set; }
        public string EventDetail { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EnterBy_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy_ID { get; set; }
        public bool IsActive { get; set; }
        public string TitleImagePath { get; set; }
        public string EventType { get; set; }
        public string EventVenue { get; set; }
        public string EventTextDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblImage> tblImages { get; set; }
    }
}
