//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFact
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Counts { get; set; }
        public string Start { get; set; }
        public string Speed { get; set; }
        public string Interval { get; set; }
    }
}
