//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvoiceDetail
    {
        public int Invoice_ID { get; set; }
        public int Book_ID { get; set; }
        public decimal SalePrice { get; set; }
        public double DiscountPercent { get; set; }
        public decimal DiscountPrice { get; set; }
        public int Quantity { get; set; }
        public int EntryByUser_ID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<int> ModifyByUser_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string BookCode { get; set; }
        public string BookISBN { get; set; }
    }
}
