//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int ImageID { get; set; }
        public int ImageType_ID { get; set; }
        public string CaptionText { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EnterBy_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy_ID { get; set; }
        public int Event_ID { get; set; }
    
        public virtual tblEvent tblEvent { get; set; }
    }
}
