//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int PaymentID { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentComments { get; set; }
        public int PaymentMode { get; set; }
        public int PaymentType { get; set; }
        public bool IsActive { get; set; }
        public int User_ID { get; set; }
    }
}
