//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityService
    {
        public int SecurityServiceID { get; set; }
        public string OrganizationName { get; set; }
        public string ContactPersonName { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> EntryDateTime { get; set; }
        public Nullable<System.DateTime> CheckDateTime { get; set; }
    }
}
