//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTeamMember
    {
        public int MemID { get; set; }
        public string MemberName { get; set; }
        public string Qualification { get; set; }
        public string Designation { get; set; }
        public string MemberContactNo { get; set; }
        public string MemberEmail { get; set; }
        public string MemberAddress { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EnterBy_ID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy_ID { get; set; }
    }
}
