//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestimonial
    {
        public int TestimonialID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string PicPath { get; set; }
        public bool IsActive { get; set; }
        public string Desg { get; set; }
        public Nullable<double> Rating { get; set; }
    }
}
