//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblText
    {
        public int TextID { get; set; }
        public string TextTitle { get; set; }
        public string TextPage { get; set; }
        public string TextDetail { get; set; }
        public byte TextType_ID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int EnterBy_ID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy_ID { get; set; }
        public string ImagePath { get; set; }
    }
}
